include ../../tests/Makefile.tests_common
# USEMODULE_INCLUDES_gds := $(LAST_MAKEFILEDIR)
# USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_gds)

USEMODULE += dht
# USEMODULE += gds
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
